<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />


    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" w="${2*arm_base_length}" h="${2*arm_base_width}" l="${2*arm_base_height}"
                           xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0" />
    </link>

    
    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${forearm_radius}" h="${forearm_length}" 
                                    xyz="0 0 ${forearm_length/2.0}" rpy="0 0 0" />
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${hand_radius}" h="${hand_length}" 
                                    xyz="0 0 ${hand_length/2.0}" rpy="0 0 0" />
    </link>


    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2.0}" effort="0" velocity="100"/>
        <!-- <dynamics friction="0.05" damping="0.1"/> -->
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2.0}" effort="0" velocity="100"/>
        <!-- <dynamics friction="0.05" damping="0.1"/> -->
    </joint>

    <gazebo>
        
        <plugin 
            filename="ignition-gazebo-joint-state-publisher-system" 
            name="ignition::gazebo::systems::JointStatePublisher">
            <joint_name>arm_base_forearm_joint</joint_name>
            <joint_name>forearm_hand_joint</joint_name>
            <topic>joint_states</topic>
            <update_rate>10</update_rate>
        </plugin>

        <plugin
            filename="libignition-gazebo-pose-publisher-system"
            name="ignition::gazebo::systems::PosePublisher">
            <publish_link_pose>true</publish_link_pose>
            <topic>pose</topic>
            <use_pose_vector_msg>true</use_pose_vector_msg>
            <static_publisher>true</static_publisher>
            <static_update_frequency>2</static_update_frequency>
        </plugin>

        <plugin
            filename="libignition-gazebo-joint-trajectory-controller-system.so"
            name="ignition::gazebo::systems::JointTrajectoryController">
            <joint_name>arm_base_forearm_joint</joint_name>
            <joint_name>forearm_hand_joint</joint_name>
            <topic>trajectory_control</topic>
            <update_rate>20</update_rate>
        </plugin>


    </gazebo>

</robot>